-- SYNTHETIC LOCAL FIXTURE, not a statement of the online schema. Never run online.
CREATE SCHEMA calc;
CREATE TABLE calc.attachment_price (
  attachment_price_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attachment_category varchar(80) NOT NULL,item_name varchar(160) NOT NULL,model_code varchar(100),variant varchar(80),
  width_mm integer,height_mm integer,depth_mm integer,price numeric(14,2),price_text varchar(120),unit varchar(20),
  price_source varchar(40),notes text,source_file text NOT NULL,source_sheet text NOT NULL,source_row_no integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);
CREATE TABLE calc.attachment_classification (
  attachment_price_id bigint PRIMARY KEY REFERENCES calc.attachment_price(attachment_price_id),
  category_level1 text NOT NULL CHECK(btrim(category_level1)<>''),
  category_level2 text CHECK(category_level2 IS NULL OR btrim(category_level2)<>''),
  category_level3 text CHECK(category_level3 IS NULL OR btrim(category_level3)<>''),
  classification_source varchar(120) NOT NULL DEFAULT 'synthetic-fixture'
);
CREATE TABLE calc.attachment_selection (
  attachment_selection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,quote_id varchar(80) NOT NULL,
  product_code varchar(40),model_code varchar(100),attachment_price_id bigint REFERENCES calc.attachment_price(attachment_price_id),
  item_name varchar(160),variant varchar(80),price_source varchar(40),quantity numeric(14,4) NOT NULL DEFAULT 1 CHECK(quantity>=0),
  unit_price numeric(14,4),price_text varchar(120),cost_method varchar(20) NOT NULL DEFAULT 'experience',notes text,
  created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now()
);
CREATE VIEW calc.v_attachment_selection_cost AS
SELECT s.*,coalesce(s.unit_price,p.price) AS effective_unit_price FROM calc.attachment_selection s LEFT JOIN calc.attachment_price p USING(attachment_price_id);
INSERT INTO calc.attachment_price(attachment_category,item_name,price,source_file,source_sheet,source_row_no) VALUES('旧分类','历史附件',12.34,'fixture','fixture',1);
INSERT INTO calc.attachment_classification(attachment_price_id,category_level1,category_level2,category_level3) VALUES(1,'旧分类',NULL,NULL);
INSERT INTO calc.attachment_selection(quote_id,product_code,attachment_price_id,item_name,unit_price) VALUES('HISTORY','JP',1,'历史附件',12.34);
