import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test, {after} from 'node:test';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const psql=process.env.ATTACHMENT_TEST_PSQL||'G:/PostgreSQL/18/bin/psql.exe';
const db=`quick_dimension_test_${Date.now()}`;
const base=['-X','-w','-h','127.0.0.1','-p','55439','-U','attachment_test','-v','ON_ERROR_STOP=1','-A','-t','-q'];
const sql=(source,database=db)=>execFileSync(psql,[...base,'-d',database],{input:source,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();

test('database quick matcher uses width first, then nearest perimeter, independent of door/model',()=>{
  sql(`CREATE DATABASE ${db};`,'postgres');
  sql(`CREATE SCHEMA calc;
    CREATE TABLE calc.quick_quote_experience(
      quick_rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_code varchar(40) NOT NULL,model_code varchar(100),material_code varchar(30) NOT NULL,
      reference_width_mm numeric NOT NULL,reference_height_mm numeric NOT NULL,reference_depth_mm numeric NOT NULL,
      min_width_mm numeric,max_width_mm numeric,min_height_mm numeric,max_height_mm numeric,min_depth_mm numeric,max_depth_mm numeric,
      quick_material_cost numeric,quick_auxiliary_cost numeric,quick_labor_cost numeric,quick_attachment_fee numeric,
      quick_spray_cost numeric,quick_management_fee numeric,quick_base_price numeric,quick_total_cost numeric NOT NULL,
      effective_from date NOT NULL,effective_to date,is_active boolean NOT NULL DEFAULT true
    );
    INSERT INTO calc.quick_quote_experience(product_code,model_code,material_code,
      reference_width_mm,reference_height_mm,reference_depth_mm,quick_base_price,quick_total_cost,effective_from)
    VALUES
      ('JE_SINGLE','同宽但周长较远','SECC',600,1500,300,1000,1000,'2026-01-01'),
      ('JE_SINGLE','同宽且周长最近','SECC',600,1700,350,1100,1100,'2026-01-01'),
      ('JE_SINGLE','异宽但周长完全一致','SECC',650,1750,400,9000,9000,'2026-01-01'),
      ('JE_DOUBLE','双门专用旧价','SECC',600,1200,300,9999,9999,'2026-01-01');`);
  sql(fs.readFileSync(path.join(root,'database/migrations/enforce_quick_quote_dimension_only.sql'),'utf8'));
  const result=JSON.parse(sql(`SELECT jsonb_build_object(
    'rows',(SELECT count(*) FROM calc.quick_quote_experience),
    'single',(SELECT jsonb_build_object(
      'id',quick_rule_id,'price',quick_total_cost,
      'width',reference_width_mm,'height',reference_height_mm,'depth',reference_depth_mm)
      FROM calc.match_quick_quote('JE_SINGLE','任意型号A','SECC',600,1800,400,'2026-08-28')),
    'double',(SELECT jsonb_build_object(
      'id',quick_rule_id,'price',quick_total_cost,
      'width',reference_width_mm,'height',reference_height_mm,'depth',reference_depth_mm)
      FROM calc.match_quick_quote('JE_DOUBLE','完全不同型号','SECC',600,1800,400,'2026-08-28'))
  )::text;`));
  assert.equal(result.rows,4);
  assert.deepEqual(result.single,result.double);
  assert.equal(Number(result.single.width),600,'same-width candidates must beat a perfect-perimeter different width');
  assert.equal(Number(result.single.height),1700,'nearest perimeter must win among same-width candidates');
  assert.equal(Number(result.single.depth),350);
  assert.ok(Number(result.single.price)<2000,'different-width 9000 face price must not be selected');

  sql(fs.readFileSync(path.join(
    root,'database/quick-quote-dimension-only-20260914/03-rollback-width-priority.sql'
  ),'utf8'));
  const rollbackDefinition=sql(`SELECT pg_get_functiondef(p.oid)
    FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='calc' AND p.proname='match_quick_quote'
      AND pg_get_function_identity_arguments(p.oid)=
      'p_product_code character varying, p_model_code character varying, p_material_code character varying, p_width_mm numeric, p_height_mm numeric, p_depth_mm numeric, p_as_of_date date';`);
  assert.match(rollbackDefinition,/ORDER BY perimeter_distance,\s*distance,\s*range_rank/);
  assert.doesNotMatch(rollbackDefinition,/width_distance/);
});

after(()=>{
  try{sql(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${db}'; DROP DATABASE IF EXISTS ${db};`,'postgres');}
  catch{}
});
