-- Web editor: execute the WHOLE file. On any error ROLLBACK; do not continue to import.
-- Installs the reviewed schema/functions in one transaction; no catalog import or switch.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';
-- Source: database/migrations/attachment_cost_v2.sql
-- Additive expansion. Does NOT change active catalog or legacy/ganged functions.
-- Review 01-readonly-preflight.sql on target first. No backup tables are created.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';
DO $$ BEGIN
  IF to_regclass('calc.attachment_price') IS NULL OR to_regclass('calc.attachment_selection') IS NULL
     OR to_regclass('calc.attachment_classification') IS NULL THEN
    RAISE EXCEPTION 'Existing attachment tables must be inspected before migration';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS calc.attachment_catalog_version (
  data_version text PRIMARY KEY,source_sha256 text NOT NULL CHECK(source_sha256 ~ '^[a-f0-9]{64}$'),
  status text NOT NULL CHECK(status IN ('STAGED','ACTIVE','RETIRED')),
  source_file text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),activated_at timestamptz,
  audit_report jsonb NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS attachment_catalog_one_active ON calc.attachment_catalog_version(status) WHERE status='ACTIVE';
ALTER TABLE calc.attachment_price
  ADD COLUMN IF NOT EXISTS quick_face_price numeric,
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS data_version text REFERENCES calc.attachment_catalog_version(data_version),
  ADD COLUMN IF NOT EXISTS import_key text,
  ADD COLUMN IF NOT EXISTS source_sha256 text;
CREATE UNIQUE INDEX IF NOT EXISTS attachment_price_version_key ON calc.attachment_price(data_version,import_key);
COMMENT ON COLUMN calc.attachment_price.quick_face_price IS 'V2权威面价：无scale限制，原样保存Excel小数。price仅为旧客户端兼容投影，不得用于V2计算。';

-- Verified online 2026-09-11: the original four-column UNIQUE blocks source reuse
-- across versions. Preserve its legacy (NULL-version) uniqueness and extend it.
-- Create the replacement before dropping the original; never use CASCADE.
DO $$
DECLARE old_definition text; new_definition text;
BEGIN
  IF current_setting('server_version_num')::integer<150000 THEN
    RAISE EXCEPTION 'Source-version uniqueness requires PostgreSQL 15 or later';
  END IF;
  SELECT pg_get_constraintdef(oid) INTO old_definition FROM pg_constraint
    WHERE conrelid='calc.attachment_price'::regclass AND conname='uq_attachment_price_source';
  IF old_definition IS NOT NULL AND old_definition<>'UNIQUE (source_file, source_sheet, source_row_no, price_source)' THEN
    RAISE EXCEPTION 'Unexpected source constraint; stop and inspect: %',old_definition;
  END IF;
  SELECT pg_get_constraintdef(oid) INTO new_definition FROM pg_constraint
    WHERE conrelid='calc.attachment_price'::regclass AND conname='uq_attachment_price_source_version';
  IF new_definition IS NULL THEN
    ALTER TABLE calc.attachment_price ADD CONSTRAINT uq_attachment_price_source_version
      UNIQUE NULLS NOT DISTINCT(source_file,source_sheet,source_row_no,price_source,data_version);
  ELSIF new_definition<>'UNIQUE NULLS NOT DISTINCT (source_file, source_sheet, source_row_no, price_source, data_version)' THEN
    RAISE EXCEPTION 'Unexpected versioned source constraint; stop and inspect: %',new_definition;
  END IF;
  IF old_definition IS NOT NULL THEN
    ALTER TABLE calc.attachment_price DROP CONSTRAINT uq_attachment_price_source;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS calc.attachment_cost_rule (
  rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_version text NOT NULL REFERENCES calc.attachment_catalog_version(data_version),import_key text NOT NULL,
  category_level1 text NOT NULL,category_level2 text NOT NULL DEFAULT '',item_name text NOT NULL,
  model_code text,color text,unit text,method text NOT NULL CHECK(method IN ('FIXED','CALCULATED')),
  fixed_cost numeric,formulas jsonb NOT NULL DEFAULT '{}',auxiliary_list text NOT NULL DEFAULT '',
  weight_not_applicable boolean NOT NULL DEFAULT false,issues jsonb NOT NULL DEFAULT '[]',
  source_file text NOT NULL,source_sheet text NOT NULL,source_row_no integer NOT NULL,
  raw_values jsonb NOT NULL,notes text,UNIQUE(data_version,import_key),UNIQUE(rule_id,data_version),
  CHECK((method='FIXED' AND fixed_cost>=0 AND fixed_cost IS NOT NULL) OR (method='CALCULATED' AND fixed_cost IS NULL))
);
CREATE TABLE IF NOT EXISTS calc.attachment_cost_rule_product (
  rule_id bigint NOT NULL REFERENCES calc.attachment_cost_rule(rule_id),product_code text NOT NULL,
  PRIMARY KEY(rule_id,product_code)
);
CREATE TABLE IF NOT EXISTS calc.attachment_cost_rule_material (
  rule_id bigint NOT NULL REFERENCES calc.attachment_cost_rule(rule_id),
  material_code text NOT NULL CHECK(material_code IN ('SECC','SUS304','SUS316')),
  PRIMARY KEY(rule_id,material_code)
);
ALTER TABLE calc.attachment_cost_rule ADD COLUMN IF NOT EXISTS model_semantics text NOT NULL DEFAULT 'MODEL'
  CHECK(model_semantics IN ('MODEL','MATERIAL','DESCRIPTION'));
CREATE TABLE IF NOT EXISTS calc.attachment_cost_rule_binding (
  attachment_price_id bigint NOT NULL REFERENCES calc.attachment_price(attachment_price_id),
  rule_id bigint NOT NULL REFERENCES calc.attachment_cost_rule(rule_id),
  PRIMARY KEY(attachment_price_id,rule_id)
);
CREATE TABLE IF NOT EXISTS calc.attachment_cost_rule_parameter (
  rule_id bigint NOT NULL REFERENCES calc.attachment_cost_rule(rule_id),name text NOT NULL,
  source text NOT NULL CHECK(source IN ('ENVIRONMENT','MANUAL')),unit text NOT NULL,
  required boolean NOT NULL,PRIMARY KEY(rule_id,name),
  CHECK((source='ENVIRONMENT' AND name IN ('宽度','高度','深度','材质密度','材质单价','喷塑单价'))
     OR (source='MANUAL' AND name NOT IN ('宽度','高度','深度','材质密度','材质单价','喷塑单价')))
);

-- Quote line identity is independent of product/model text and exists before document confirmation.
CREATE TABLE IF NOT EXISTS calc.attachment_quote_line (
  quote_line_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),quote_id varchar(80) NOT NULL,
  product_code varchar(40) NOT NULL,environment_snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(quote_line_id,quote_id),
  CHECK(jsonb_typeof(environment_snapshot)='object'
    AND environment_snapshot ?& ARRAY['product_code','width_mm','height_mm','depth_mm','material_code','density_g_cm3','material_unit_price','spray_unit_price','coating_type','quote_date']
    AND environment_snapshot->>'product_code'=product_code
    AND jsonb_typeof(environment_snapshot->'width_mm')='number' AND (environment_snapshot->>'width_mm')::numeric>0
    AND jsonb_typeof(environment_snapshot->'height_mm')='number' AND (environment_snapshot->>'height_mm')::numeric>0
    AND jsonb_typeof(environment_snapshot->'depth_mm')='number' AND (environment_snapshot->>'depth_mm')::numeric>0)
);
ALTER TABLE calc.attachment_selection
  ADD COLUMN IF NOT EXISTS quote_line_id uuid,
  ADD COLUMN IF NOT EXISTS price_sign smallint NOT NULL DEFAULT 1 CHECK(price_sign IN (-1,1)),
  ADD COLUMN IF NOT EXISTS calculation_status text,
  ADD COLUMN IF NOT EXISTS cost_rule_id bigint,
  ADD COLUMN IF NOT EXISTS rule_version text,
  ADD COLUMN IF NOT EXISTS catalog_version text REFERENCES calc.attachment_catalog_version(data_version),
  ADD COLUMN IF NOT EXISTS manual_inputs jsonb,
  ADD COLUMN IF NOT EXISTS environment_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS quick_face_price numeric,
  ADD COLUMN IF NOT EXISTS quick_amount numeric,
  ADD COLUMN IF NOT EXISTS formula_unit_cost numeric,
  ADD COLUMN IF NOT EXISTS formula_amount numeric,
  ADD COLUMN IF NOT EXISTS cost_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS error_message text;
DO $$ BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='calc.attachment_selection'::regclass AND conname='attachment_selection_v2_line_fk') THEN
    ALTER TABLE calc.attachment_selection ADD CONSTRAINT attachment_selection_v2_line_fk FOREIGN KEY(quote_line_id,quote_id) REFERENCES calc.attachment_quote_line(quote_line_id,quote_id);
    ALTER TABLE calc.attachment_selection ADD CONSTRAINT attachment_selection_v2_rule_fk FOREIGN KEY(cost_rule_id,rule_version) REFERENCES calc.attachment_cost_rule(rule_id,data_version);
    ALTER TABLE calc.attachment_selection ADD CONSTRAINT attachment_selection_v2_state CHECK (
      (calculation_status IS NULL AND quote_line_id IS NULL) OR (
        calculation_status IS NOT NULL AND calculation_status IN ('FIXED','CALCULATED','QUICK_ONLY','ERROR') AND quote_line_id IS NOT NULL
        AND attachment_price_id IS NOT NULL AND catalog_version IS NOT NULL
        AND quick_face_price IS NOT NULL AND quick_face_price>=0 AND quick_amount IS NOT NULL
        AND manual_inputs IS NOT NULL AND environment_snapshot IS NOT NULL AND cost_snapshot IS NOT NULL
        AND jsonb_typeof(manual_inputs)='object' AND jsonb_typeof(cost_snapshot)='object'
        AND quick_amount=round(quantity*quick_face_price*price_sign,2)
        AND ((calculation_status IN ('FIXED','CALCULATED') AND cost_rule_id IS NOT NULL AND rule_version IS NOT NULL AND formula_unit_cost IS NOT NULL AND formula_unit_cost>=0 AND formula_amount IS NOT NULL AND formula_amount=round(quantity*formula_unit_cost*price_sign,2))
          OR (calculation_status='QUICK_ONLY' AND cost_rule_id IS NULL AND formula_amount IS NULL AND formula_unit_cost IS NULL)
          OR (calculation_status='ERROR' AND formula_amount IS NULL AND formula_unit_cost IS NULL AND length(error_message)>0 AND error_message IS NOT NULL))
      ));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS attachment_selection_v2_line ON calc.attachment_selection(quote_line_id) WHERE quote_line_id IS NOT NULL;

CREATE OR REPLACE VIEW calc.v_attachment_selection_dual_cost AS
SELECT s.attachment_selection_id,s.quote_id,s.quote_line_id,s.attachment_price_id,s.quantity,s.price_sign,
       s.calculation_status,s.quick_face_price,s.quick_amount,s.formula_unit_cost,s.formula_amount,
       s.cost_rule_id,s.rule_version,s.catalog_version,s.manual_inputs,s.environment_snapshot,s.cost_snapshot,s.error_message
FROM calc.attachment_selection s WHERE s.calculation_status IS NOT NULL;
COMMENT ON VIEW calc.v_attachment_selection_dual_cost IS '仅快照，无当前目录回查；历史legacy记录不会被虚构为FIXED或QUICK_ONLY。';

CREATE OR REPLACE VIEW calc.v_attachment_catalog_v2 AS
SELECT ap.attachment_price_id,c.category_level1,coalesce(c.category_level2,'') AS category_level2,coalesce(c.category_level3,'') AS category_level3,
       ap.item_name,ap.model_code,ap.unit,ap.color,ap.width_mm,ap.height_mm,ap.depth_mm,
       ap.quick_face_price AS price,ap.data_version,ap.source_file,ap.source_sheet,ap.source_row_no,ap.source_sha256
FROM calc.attachment_price ap JOIN calc.attachment_classification c USING(attachment_price_id)
JOIN calc.attachment_catalog_version v ON v.data_version=ap.data_version
WHERE ap.is_active AND v.status='ACTIVE';
COMMENT ON VIEW calc.v_attachment_catalog_v2 IS 'V2目录接口必须读此视图：price为完整精度面价，按ID保留不同分类，不做名称去重。';

CREATE OR REPLACE FUNCTION calc.get_attachment_dual_fee(p_quote_line_id uuid)
RETURNS TABLE(quick_fee numeric,formula_fee numeric,error_count bigint,quick_only_count bigint)
LANGUAGE sql STABLE AS $$
  SELECT coalesce(sum(quick_amount),0),
         CASE WHEN count(*) FILTER(WHERE calculation_status='ERROR')>0 THEN NULL ELSE coalesce(sum(formula_amount) FILTER(WHERE calculation_status IN ('FIXED','CALCULATED')),0) END,
         count(*) FILTER(WHERE calculation_status='ERROR'),count(*) FILTER(WHERE calculation_status='QUICK_ONLY')
  FROM calc.v_attachment_selection_dual_cost WHERE quote_line_id=p_quote_line_id;
$$;
CREATE OR REPLACE FUNCTION calc.get_attachment_formula_fee_strict(p_quote_line_id uuid)
RETURNS numeric LANGUAGE plpgsql STABLE AS $$ DECLARE fees record; BEGIN
  IF NOT EXISTS(SELECT 1 FROM calc.attachment_quote_line WHERE quote_line_id=p_quote_line_id) THEN RAISE EXCEPTION '报价行不存在'; END IF;
  SELECT * INTO fees FROM calc.get_attachment_dual_fee(p_quote_line_id);
  IF fees.error_count>0 THEN RAISE EXCEPTION '附件成本计算失败，不能生成完整公式报价（%项）',fees.error_count; END IF;
  RETURN fees.formula_fee;
END $$;

-- Select specificity before checking rule issues: broken specific rules never fall back to generic.
CREATE OR REPLACE FUNCTION calc.resolve_attachment_cost_rule(p_attachment_price_id bigint,p_product_code text,p_material_code text)
RETURNS bigint LANGUAGE plpgsql STABLE AS $$ DECLARE candidates bigint[]; product_candidates bigint[]; BEGIN
  SELECT array_agg(r.rule_id) INTO product_candidates
  FROM calc.attachment_cost_rule_binding b JOIN calc.attachment_cost_rule r USING(rule_id)
  WHERE b.attachment_price_id=p_attachment_price_id AND
    (NOT EXISTS(SELECT 1 FROM calc.attachment_cost_rule_product p WHERE p.rule_id=r.rule_id)
     OR EXISTS(SELECT 1 FROM calc.attachment_cost_rule_product p WHERE p.rule_id=r.rule_id AND p.product_code=p_product_code));
  IF coalesce(cardinality(product_candidates),0)=0 THEN RETURN NULL; END IF;
  IF EXISTS(SELECT 1 FROM calc.attachment_cost_rule_material m WHERE m.rule_id=ANY(product_candidates))
    AND (p_material_code IS NULL OR p_material_code NOT IN ('SECC','SUS304','SUS316')) THEN
    RAISE EXCEPTION '材质适用规则需要有效材质：SECC、SUS304或SUS316';
  END IF;
  WITH candidates AS (
    SELECT r.rule_id,CASE WHEN EXISTS(SELECT 1 FROM calc.attachment_cost_rule_product p WHERE p.rule_id=r.rule_id AND p.product_code=p_product_code) THEN 1 ELSE 0 END AS priority
    FROM calc.attachment_cost_rule_binding b JOIN calc.attachment_cost_rule r USING(rule_id)
    WHERE b.attachment_price_id=p_attachment_price_id AND r.rule_id=ANY(product_candidates) AND
      (NOT EXISTS(SELECT 1 FROM calc.attachment_cost_rule_material m WHERE m.rule_id=r.rule_id)
       OR EXISTS(SELECT 1 FROM calc.attachment_cost_rule_material m WHERE m.rule_id=r.rule_id AND m.material_code=p_material_code))
  ) SELECT array_agg(rule_id) INTO candidates FROM candidates WHERE priority=(SELECT max(priority) FROM candidates);
  IF coalesce(cardinality(candidates),0)=0 THEN RAISE EXCEPTION '当前材质 % 缺少附件成本规则',p_material_code; END IF;
  IF cardinality(candidates)>1 THEN RAISE EXCEPTION '同级成本规则冲突：%',candidates; END IF;
  RETURN candidates[1];
END $$;
-- Old V2 callers may resolve unrestricted rules; material-dependent rules require the third argument.
CREATE OR REPLACE FUNCTION calc.resolve_attachment_cost_rule(p_attachment_price_id bigint,p_product_code text)
RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT calc.resolve_attachment_cost_rule(p_attachment_price_id,p_product_code,NULL::text);
$$;
REVOKE ALL ON FUNCTION calc.resolve_attachment_cost_rule(bigint,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION calc.resolve_attachment_cost_rule(bigint,text,text) FROM PUBLIC;

-- Source: database/attachment-v2/02-import-functions.sql
SET LOCAL lock_timeout='5s';
CREATE OR REPLACE FUNCTION calc.stage_attachment_catalog_v2(bundle jsonb)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE v text:=bundle->>'data_version'; q jsonb; r jsonb; p jsonb; material text; price_id bigint; new_rule_id bigint; legacy_scale integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('calc.attachment_catalog_v2'));
  IF v IS NULL OR length(v)=0 OR bundle->>'source_sha256' IS NULL THEN RAISE EXCEPTION 'Missing import provenance'; END IF;
  IF jsonb_typeof(bundle->'report'->'issues') IS DISTINCT FROM 'array'
     OR jsonb_array_length(bundle->'report'->'issues')<>0
     OR jsonb_typeof(bundle->'report'->'unmapped_rules') IS DISTINCT FROM 'array'
     OR jsonb_array_length(bundle->'report'->'unmapped_rules')<>0 THEN
    RAISE EXCEPTION '附件源数据存在待确认/未映射问题；禁止正式导入：%',bundle->'report'->'issues';
  END IF;
  IF jsonb_typeof(bundle->'catalog') IS DISTINCT FROM 'array' OR jsonb_array_length(bundle->'catalog')=0
    OR jsonb_typeof(bundle->'rules') IS DISTINCT FROM 'array' OR jsonb_typeof(bundle->'bindings') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Invalid import arrays'; END IF;
  IF (bundle#>>'{report,counts,quick}')::integer IS DISTINCT FROM jsonb_array_length(bundle->'catalog')
    OR (bundle#>>'{report,counts,rules}')::integer IS DISTINCT FROM jsonb_array_length(bundle->'rules')
    OR (bundle#>>'{report,counts,bindings}')::integer IS DISTINCT FROM jsonb_array_length(bundle->'bindings') THEN RAISE EXCEPTION 'Import counts differ from audit report'; END IF;
  IF EXISTS(SELECT 1 FROM calc.attachment_catalog_version WHERE data_version=v) THEN RAISE EXCEPTION 'Version already staged; inspect instead of duplicating: %',v; END IF;
  SELECT numeric_scale INTO legacy_scale FROM information_schema.columns
  WHERE table_schema='calc' AND table_name='attachment_price' AND column_name='price' AND data_type='numeric';
  IF NOT FOUND THEN RAISE EXCEPTION 'Legacy price column must be numeric; inspect target schema'; END IF;
  INSERT INTO calc.attachment_catalog_version(data_version,source_sha256,status,source_file,audit_report)
  VALUES(v,bundle->>'source_sha256','STAGED',bundle->'catalog'->0->>'source_file',bundle->'report');
  FOR q IN SELECT value FROM jsonb_array_elements(bundle->'catalog') LOOP
    IF jsonb_typeof(q->'price') IS DISTINCT FROM 'number' OR (q->>'price')::numeric<0
      OR q->>'data_version' IS DISTINCT FROM v OR nullif(q->>'import_key','') IS NULL THEN RAISE EXCEPTION 'Invalid quick price/source: %',q; END IF;
    INSERT INTO calc.attachment_price(attachment_category,item_name,model_code,variant,width_mm,height_mm,depth_mm,
      price,quick_face_price,price_text,unit,price_source,source_file,source_sheet,source_row_no,is_active,color,data_version,import_key,source_sha256,notes)
    VALUES(q->>'category_level1',q->>'item_name',nullif(q->>'model_code',''),NULL,(q->>'width_mm')::integer,(q->>'height_mm')::integer,(q->>'depth_mm')::integer,
      CASE WHEN legacy_scale IS NULL THEN (q->>'price')::numeric ELSE round((q->>'price')::numeric,legacy_scale) END,
      (q->>'price')::numeric,q->>'price',nullif(q->>'unit',''),'Excel',q->>'source_file',q->>'source_sheet',(q->>'source_row_no')::integer,false,q->>'color',v,q->>'import_key',bundle->>'source_sha256',
      'V2面价见quick_face_price；price为明确舍入的旧字段兼容投影，禁止V2计算使用') RETURNING attachment_price_id INTO price_id;
    INSERT INTO calc.attachment_classification(attachment_price_id,category_level1,category_level2,category_level3,classification_source)
    VALUES(price_id,q->>'category_level1',nullif(q->>'category_level2',''),NULL,v);
  END LOOP;
  FOR r IN SELECT value FROM jsonb_array_elements(bundle->'rules') LOOP
    IF r->>'data_version' IS DISTINCT FROM v OR jsonb_typeof(r->'issues') IS DISTINCT FROM 'array' OR jsonb_array_length(r->'issues')>0 THEN RAISE EXCEPTION 'Unresolved rule: %',r->>'import_key'; END IF;
    INSERT INTO calc.attachment_cost_rule(data_version,import_key,category_level1,category_level2,item_name,model_code,color,unit,
      method,fixed_cost,formulas,auxiliary_list,weight_not_applicable,issues,source_file,source_sheet,source_row_no,raw_values,notes)
    VALUES(v,r->>'import_key',r->>'category_level1',r->>'category_level2',r->>'item_name',r->>'model_code',r->>'color',r->>'unit',
      r->>'method',(r->>'fixed_cost')::numeric,r->'formulas',r->>'auxiliary_list',coalesce((r->>'weight_not_applicable')::boolean,false),r->'issues',r->>'source_file',r->>'source_sheet',(r->>'source_row_no')::integer,r->'raw_values',r->>'notes')
    RETURNING rule_id INTO new_rule_id;
    UPDATE calc.attachment_cost_rule SET model_semantics=coalesce(r->>'model_semantics','MODEL') WHERE rule_id=new_rule_id;
    INSERT INTO calc.attachment_cost_rule_product(rule_id,product_code) SELECT new_rule_id,value FROM jsonb_array_elements_text(r->'products');
    IF jsonb_typeof(r->'materials') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Missing material applicability array'; END IF;
    INSERT INTO calc.attachment_cost_rule_material(rule_id,material_code) SELECT new_rule_id,value FROM jsonb_array_elements_text(r->'materials');
    FOR p IN SELECT value FROM jsonb_array_elements(r->'parameters') LOOP
      INSERT INTO calc.attachment_cost_rule_parameter(rule_id,name,source,unit,required)
      VALUES(new_rule_id,p->>'name',p->>'source',p->>'unit',(p->>'required')::boolean);
    END LOOP;
  END LOOP;
  INSERT INTO calc.attachment_cost_rule_binding(attachment_price_id,rule_id)
  SELECT ap.attachment_price_id,cr.rule_id FROM jsonb_array_elements(bundle->'bindings') b
  JOIN calc.attachment_price ap ON ap.data_version=v AND ap.import_key=b->>'attachment_key'
  JOIN calc.attachment_cost_rule cr ON cr.data_version=v AND cr.import_key=b->>'rule_key';
  IF (SELECT count(*) FROM calc.attachment_cost_rule_binding b JOIN calc.attachment_price ap USING(attachment_price_id) WHERE ap.data_version=v)<>jsonb_array_length(bundle->'bindings') THEN RAISE EXCEPTION 'Invalid or missing binding keys'; END IF;
  IF EXISTS(SELECT 1 FROM calc.attachment_cost_rule r WHERE r.data_version=v AND NOT EXISTS(SELECT 1 FROM calc.attachment_cost_rule_binding b WHERE b.rule_id=r.rule_id)) THEN RAISE EXCEPTION 'Unmapped cost rules'; END IF;
  -- No automatic name-only fallback, including null/blank secondary classifications.
  IF EXISTS(SELECT 1 FROM calc.attachment_cost_rule_binding b JOIN calc.attachment_price ap USING(attachment_price_id)
    JOIN calc.attachment_classification c USING(attachment_price_id) JOIN calc.attachment_cost_rule r USING(rule_id)
    WHERE ap.data_version=v AND (r.data_version<>v OR r.category_level1 IS DISTINCT FROM c.category_level1 OR r.category_level2 IS DISTINCT FROM coalesce(c.category_level2,'') OR r.item_name IS DISTINCT FROM ap.item_name)) THEN RAISE EXCEPTION 'Cross-classification or cross-version binding'; END IF;
  -- Check generic and every explicitly supported product separately; never LIMIT 1.
  FOR q IN SELECT to_jsonb(ap) FROM calc.attachment_price ap WHERE ap.data_version=v LOOP
    FOREACH material IN ARRAY ARRAY['SECC','SUS304','SUS316'] LOOP
      PERFORM calc.resolve_attachment_cost_rule((q->>'attachment_price_id')::bigint,'__GENERIC__',material);
      FOR p IN SELECT DISTINCT to_jsonb(product_code) FROM calc.attachment_cost_rule_product pr JOIN calc.attachment_cost_rule r USING(rule_id) WHERE r.data_version=v LOOP
        PERFORM calc.resolve_attachment_cost_rule((q->>'attachment_price_id')::bigint,p#>>'{}',material);
      END LOOP;
    END LOOP;
  END LOOP;
  RETURN v;
END $$;

CREATE OR REPLACE FUNCTION calc.switch_attachment_catalog_v2(v text)
RETURNS text LANGUAGE plpgsql AS $$ BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('calc.attachment_catalog_v2'));
  IF current_setting('calc.attachment_v2_api_ready',true) IS DISTINCT FROM 'on' THEN
    RAISE EXCEPTION '尚未确认API/客户端V2兼容；仅允许扩展建表，禁止切换活动目录';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM calc.attachment_catalog_version WHERE data_version=v AND status='STAGED') THEN RAISE EXCEPTION 'Expected staged version: %',v; END IF;
  -- Blocks concurrent catalog writers for this short transaction, ordinary readers continue.
  LOCK TABLE calc.attachment_price IN SHARE ROW EXCLUSIVE MODE;
  UPDATE calc.attachment_price SET is_active=false WHERE is_active AND data_version IS DISTINCT FROM v;
  UPDATE calc.attachment_catalog_version SET status='RETIRED' WHERE status='ACTIVE';
  UPDATE calc.attachment_price SET is_active=true WHERE data_version=v;
  UPDATE calc.attachment_catalog_version SET status='ACTIVE',activated_at=now() WHERE data_version=v;
  RETURN v;
END $$;
CREATE OR REPLACE FUNCTION calc.activate_attachment_catalog_v2(bundle jsonb)
RETURNS text LANGUAGE plpgsql AS $$ DECLARE v text; BEGIN
  v:=calc.stage_attachment_catalog_v2(bundle);
  RETURN calc.switch_attachment_catalog_v2(v);
END $$;
REVOKE ALL ON FUNCTION calc.stage_attachment_catalog_v2(jsonb),calc.switch_attachment_catalog_v2(text),calc.activate_attachment_catalog_v2(jsonb) FROM PUBLIC;

-- Source: database/attachment-v2/02b-snapshot-guards.sql
SET LOCAL lock_timeout='5s';
CREATE OR REPLACE FUNCTION calc.guard_attachment_selection_v2()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE ap calc.attachment_price%ROWTYPE; owner_line calc.attachment_quote_line%ROWTYPE; rule calc.attachment_cost_rule%ROWTYPE; expected_rule bigint; classification calc.attachment_classification%ROWTYPE;
BEGIN
  IF TG_OP IN ('UPDATE','DELETE') AND OLD.calculation_status IS NOT NULL THEN
    RAISE EXCEPTION 'V2附件报价快照不可覆盖或删除；请新建报价行版本';
  END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  IF NEW.calculation_status IS NULL THEN RETURN NEW; END IF;
  SELECT * INTO STRICT ap FROM calc.attachment_price WHERE attachment_price_id=NEW.attachment_price_id;
  SELECT * INTO STRICT classification FROM calc.attachment_classification WHERE attachment_price_id=NEW.attachment_price_id;
  SELECT * INTO STRICT owner_line FROM calc.attachment_quote_line WHERE quote_line_id=NEW.quote_line_id;
  IF NEW.quote_id IS DISTINCT FROM owner_line.quote_id OR NEW.product_code IS DISTINCT FROM owner_line.product_code
    OR NEW.environment_snapshot IS DISTINCT FROM owner_line.environment_snapshot THEN RAISE EXCEPTION '附件归属或报价环境不一致'; END IF;
  IF NEW.catalog_version IS DISTINCT FROM ap.data_version OR NEW.quick_face_price IS DISTINCT FROM ap.quick_face_price THEN RAISE EXCEPTION '附件目录版本或面价不一致'; END IF;
  IF NEW.price_sign=-1 AND (position('安装板' IN ap.item_name||' '||coalesce(ap.attachment_category,''))=0
    OR position('安装板单发' IN ap.item_name||' '||coalesce(ap.attachment_category,''))>0) THEN RAISE EXCEPTION '该附件不允许扣减'; END IF;
  IF NOT NEW.cost_snapshot ?& ARRAY['item_name','category_level1','category_level2','unit','auxiliary_list'] THEN RAISE EXCEPTION '缺少附件身份/辅材清单快照'; END IF;
  IF NEW.cost_snapshot->>'item_name' IS DISTINCT FROM ap.item_name
    OR NEW.cost_snapshot->>'category_level1' IS DISTINCT FROM classification.category_level1
    OR NEW.cost_snapshot->>'category_level2' IS DISTINCT FROM coalesce(classification.category_level2,'')
    OR NEW.cost_snapshot->>'unit' IS DISTINCT FROM coalesce(ap.unit,'') THEN RAISE EXCEPTION '附件身份或单位快照不一致'; END IF;
  IF NEW.calculation_status<>'ERROR' THEN
    expected_rule:=calc.resolve_attachment_cost_rule(NEW.attachment_price_id,NEW.product_code,owner_line.environment_snapshot->>'material_code');
    IF NEW.cost_rule_id IS DISTINCT FROM expected_rule THEN RAISE EXCEPTION '所选成本规则不是当前产品适用规则'; END IF;
    IF expected_rule IS NOT NULL THEN
      SELECT * INTO STRICT rule FROM calc.attachment_cost_rule WHERE rule_id=expected_rule;
      IF rule.issues<>'[]'::jsonb THEN RAISE EXCEPTION '成本规则仍有待确认事项'; END IF;
      IF NEW.rule_version IS DISTINCT FROM rule.data_version OR NEW.cost_snapshot->>'auxiliary_list' IS DISTINCT FROM rule.auxiliary_list THEN RAISE EXCEPTION '成本规则版本或辅材清单不一致'; END IF;
      IF NEW.calculation_status='FIXED' AND (rule.method<>'FIXED' OR NEW.formula_unit_cost IS DISTINCT FROM rule.fixed_cost) THEN RAISE EXCEPTION '固定成本不一致'; END IF;
      IF NEW.calculation_status='CALCULATED' THEN
        IF rule.method<>'CALCULATED' OR NOT NEW.cost_snapshot ?& ARRAY['weight_kg','material_cost','spray_area_m2','spray_cost','auxiliary_cost','labor_cost'] THEN RAISE EXCEPTION '缺少动态成本组成'; END IF;
        IF EXISTS(SELECT 1 FROM unnest(ARRAY['material_cost','spray_area_m2','spray_cost','auxiliary_cost','labor_cost']) k WHERE jsonb_typeof(NEW.cost_snapshot->k) IS DISTINCT FROM 'number' OR (NEW.cost_snapshot->>k)::numeric<0) THEN RAISE EXCEPTION '动态成本组成必须是非负数'; END IF;
        IF round(NEW.formula_unit_cost,8) IS DISTINCT FROM round((NEW.cost_snapshot->>'material_cost')::numeric+(NEW.cost_snapshot->>'spray_cost')::numeric+(NEW.cost_snapshot->>'auxiliary_cost')::numeric+(NEW.cost_snapshot->>'labor_cost')::numeric,8) THEN RAISE EXCEPTION '成本组成与单位成本不一致'; END IF;
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS attachment_selection_v2_guard ON calc.attachment_selection;
CREATE TRIGGER attachment_selection_v2_guard BEFORE INSERT OR UPDATE OR DELETE ON calc.attachment_selection
FOR EACH ROW EXECUTE FUNCTION calc.guard_attachment_selection_v2();
CREATE OR REPLACE FUNCTION calc.guard_attachment_quote_line_v2()
RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
  RAISE EXCEPTION '报价行环境快照不可变；请创建新报价行ID';
END $$;
DROP TRIGGER IF EXISTS attachment_quote_line_v2_guard ON calc.attachment_quote_line;
CREATE TRIGGER attachment_quote_line_v2_guard BEFORE UPDATE OR DELETE ON calc.attachment_quote_line
FOR EACH ROW EXECUTE FUNCTION calc.guard_attachment_quote_line_v2();

SELECT 'READY: schema prepared; current catalog and quotation history retained' AS result;
COMMIT;
