-- Attachment selection and fee aggregation.
-- All attachment prices are experience values; this table stores the selected
-- price snapshot per quote and aggregates it into attachment_fee.
BEGIN;

CREATE TABLE IF NOT EXISTS calc.attachment_selection (
  attachment_selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id VARCHAR(80) NOT NULL,
  product_code VARCHAR(40),
  model_code VARCHAR(100),
  attachment_price_id BIGINT REFERENCES calc.attachment_price(attachment_price_id),
  item_name VARCHAR(160),
  variant VARCHAR(80),
  price_source VARCHAR(40),
  quantity NUMERIC(14, 4) NOT NULL DEFAULT 1 CHECK (quantity >= 0),
  unit_price NUMERIC(14, 4) CHECK (unit_price IS NULL OR unit_price >= 0),
  price_text VARCHAR(120),
  cost_method VARCHAR(20) NOT NULL DEFAULT 'experience',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attachment_selection_quote
  ON calc.attachment_selection(quote_id, product_code);
CREATE INDEX IF NOT EXISTS idx_attachment_selection_model
  ON calc.attachment_selection(model_code, item_name);

CREATE OR REPLACE VIEW calc.v_attachment_selection_cost AS
SELECT
  s.attachment_selection_id,
  s.quote_id,
  s.product_code,
  s.model_code,
  s.attachment_price_id,
  s.item_name,
  s.variant,
  s.price_source,
  s.quantity,
  s.unit_price,
  s.price_text,
  s.cost_method,
  COALESCE(s.unit_price, p.price) AS effective_unit_price,
  CASE
    WHEN COALESCE(s.unit_price, p.price) IS NULL THEN NULL
    ELSE ROUND(s.quantity * COALESCE(s.unit_price, p.price), 2)
  END AS line_cost,
  s.notes,
  s.created_at,
  s.updated_at
FROM calc.attachment_selection s
LEFT JOIN calc.attachment_price p
  ON p.attachment_price_id = s.attachment_price_id;

CREATE OR REPLACE FUNCTION calc.get_attachment_fee(
  p_quote_id VARCHAR,
  p_product_code VARCHAR DEFAULT NULL
)
RETURNS NUMERIC
LANGUAGE SQL
STABLE
AS $function$
  SELECT COALESCE(ROUND(SUM(v.line_cost), 2), 0)
  FROM calc.v_attachment_selection_cost v
  WHERE v.quote_id = p_quote_id
    AND (p_product_code IS NULL OR v.product_code = p_product_code);
$function$;

CREATE OR REPLACE FUNCTION calc.add_attachment_selection(
  p_quote_id VARCHAR,
  p_product_code VARCHAR DEFAULT NULL,
  p_model_code VARCHAR DEFAULT NULL,
  p_item_name VARCHAR DEFAULT NULL,
  p_quantity NUMERIC DEFAULT 1,
  p_width_mm INTEGER DEFAULT NULL,
  p_height_mm INTEGER DEFAULT NULL,
  p_depth_mm INTEGER DEFAULT NULL,
  p_variant VARCHAR DEFAULT NULL,
  p_price_source VARCHAR DEFAULT NULL,
  p_unit_price_override NUMERIC DEFAULT NULL,
  p_notes TEXT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
VOLATILE
AS $function$
DECLARE
  v_price calc.attachment_price%ROWTYPE;
  v_selection_id BIGINT;
BEGIN
  IF p_quote_id IS NULL OR btrim(p_quote_id) = '' THEN
    RAISE EXCEPTION 'quote_id is required';
  END IF;
  IF p_model_code IS NULL AND p_item_name IS NULL THEN
    RAISE EXCEPTION 'model_code or item_name is required';
  END IF;
  IF p_quantity IS NULL OR p_quantity < 0 THEN
    RAISE EXCEPTION 'quantity must be non-negative';
  END IF;

  SELECT ap.*
  INTO v_price
  FROM calc.attachment_price ap
  WHERE ap.is_active = TRUE
    AND (p_model_code IS NULL OR ap.model_code = p_model_code OR ap.model_code IS NULL OR ap.model_code = '所有型号')
    AND (p_item_name IS NULL OR ap.item_name = p_item_name)
    AND (p_width_mm IS NULL OR ap.width_mm = p_width_mm)
    AND (p_height_mm IS NULL OR ap.height_mm = p_height_mm)
    AND (p_depth_mm IS NULL OR ap.depth_mm = p_depth_mm)
    AND (p_variant IS NULL OR ap.variant = p_variant OR ap.variant IS NULL)
    AND (p_price_source IS NULL OR ap.price_source = p_price_source)
  ORDER BY
    CASE WHEN ap.model_code = p_model_code THEN 0 ELSE 1 END,
    CASE WHEN ap.item_name = p_item_name THEN 0 ELSE 1 END,
    ap.attachment_price_id DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'attachment price not found: model=%, item=%, variant=%, source=%',
      p_model_code, p_item_name, p_variant, p_price_source;
  END IF;

  INSERT INTO calc.attachment_selection (
    quote_id, product_code, model_code, attachment_price_id,
    item_name, variant, price_source, quantity, unit_price,
    price_text, cost_method, notes
  )
  VALUES (
    p_quote_id, p_product_code, v_price.model_code, v_price.attachment_price_id,
    v_price.item_name, v_price.variant, v_price.price_source, p_quantity,
    COALESCE(p_unit_price_override, v_price.price), v_price.price_text,
    'experience', p_notes
  )
  RETURNING attachment_selection_id INTO v_selection_id;

  RETURN v_selection_id;
END;
$function$;

-- Ensure the base total-cost function exists before creating the quote wrapper.
CREATE OR REPLACE FUNCTION calc.calculate_total_cost_by_spray_cost(
  p_corrected_material_weight_kg NUMERIC,
  p_material_price_per_kg NUMERIC,
  p_auxiliary_cost NUMERIC DEFAULT 0,
  p_labor_cost NUMERIC DEFAULT 0,
  p_attachment_fee NUMERIC DEFAULT 0,
  p_spray_cost NUMERIC DEFAULT 0
)
RETURNS TABLE (
  material_cost NUMERIC,
  auxiliary_cost NUMERIC,
  labor_cost NUMERIC,
  attachment_fee NUMERIC,
  spray_cost NUMERIC,
  management_fee NUMERIC,
  total_cost NUMERIC
)
LANGUAGE SQL
IMMUTABLE
AS $function$
  SELECT ROUND(p_corrected_material_weight_kg * p_material_price_per_kg, 2),
         ROUND(COALESCE(p_auxiliary_cost, 0), 2),
         ROUND(COALESCE(p_labor_cost, 0), 2),
         ROUND(COALESCE(p_attachment_fee, 0), 2),
         ROUND(COALESCE(p_spray_cost, 0), 2),
         ROUND(COALESCE(p_labor_cost, 0) * 0.13, 2),
         ROUND(
           p_corrected_material_weight_kg * p_material_price_per_kg
           + COALESCE(p_auxiliary_cost, 0)
           + COALESCE(p_labor_cost, 0)
           + COALESCE(p_attachment_fee, 0)
           + COALESCE(p_spray_cost, 0)
           + COALESCE(p_labor_cost, 0) * 0.13,
           2
         );
$function$;

CREATE OR REPLACE FUNCTION calc.calculate_total_cost_for_quote(
  p_quote_id VARCHAR,
  p_corrected_material_weight_kg NUMERIC,
  p_material_price_per_kg NUMERIC,
  p_auxiliary_cost NUMERIC DEFAULT 0,
  p_labor_cost NUMERIC DEFAULT 0,
  p_spray_cost NUMERIC DEFAULT 0,
  p_product_code VARCHAR DEFAULT NULL
)
RETURNS TABLE (
  material_cost NUMERIC,
  auxiliary_cost NUMERIC,
  labor_cost NUMERIC,
  attachment_fee NUMERIC,
  spray_cost NUMERIC,
  management_fee NUMERIC,
  total_cost NUMERIC
)
LANGUAGE SQL
STABLE
AS $function$
  SELECT *
  FROM calc.calculate_total_cost_by_spray_cost(
    p_corrected_material_weight_kg,
    p_material_price_per_kg,
    p_auxiliary_cost,
    p_labor_cost,
    calc.get_attachment_fee(p_quote_id, p_product_code),
    p_spray_cost
  );
$function$;

COMMENT ON TABLE calc.attachment_selection
IS 'Selected attachment experience-price lines for a quote; all attachment costs use experience values.';
COMMENT ON FUNCTION calc.get_attachment_fee(VARCHAR, VARCHAR)
IS 'Aggregates numeric attachment line prices for a quote; non-numeric price_text lines are excluded until overridden.';

-- Ensure the base total-cost function exists before creating the quote wrapper.
CREATE OR REPLACE FUNCTION calc.calculate_total_cost_by_spray_cost(
  p_corrected_material_weight_kg NUMERIC,
  p_material_price_per_kg NUMERIC,
  p_auxiliary_cost NUMERIC DEFAULT 0,
  p_labor_cost NUMERIC DEFAULT 0,
  p_attachment_fee NUMERIC DEFAULT 0,
  p_spray_cost NUMERIC DEFAULT 0
)
RETURNS TABLE (
  material_cost NUMERIC,
  auxiliary_cost NUMERIC,
  labor_cost NUMERIC,
  attachment_fee NUMERIC,
  spray_cost NUMERIC,
  management_fee NUMERIC,
  total_cost NUMERIC
)
LANGUAGE SQL
IMMUTABLE
AS $function$
  WITH inputs AS (
    SELECT
      p_corrected_material_weight_kg * p_material_price_per_kg AS material_cost_raw,
      COALESCE(p_auxiliary_cost, 0) AS auxiliary_cost_raw,
      COALESCE(p_labor_cost, 0) AS labor_cost_raw,
      COALESCE(p_attachment_fee, 0) AS attachment_fee_raw,
      COALESCE(p_spray_cost, 0) AS spray_cost_raw
  ), components AS (
    SELECT
      ROUND(material_cost_raw, 2) AS material_cost,
      ROUND(auxiliary_cost_raw, 2) AS auxiliary_cost,
      ROUND(labor_cost_raw, 2) AS labor_cost,
      ROUND(attachment_fee_raw, 2) AS attachment_fee,
      ROUND(spray_cost_raw, 2) AS spray_cost,
      ROUND(labor_cost_raw * 0.13, 2) AS management_fee,
      material_cost_raw + auxiliary_cost_raw + labor_cost_raw
        + attachment_fee_raw + spray_cost_raw + labor_cost_raw * 0.13 AS total_cost_raw
    FROM inputs
  )
  SELECT material_cost,
         auxiliary_cost,
         labor_cost,
         attachment_fee,
         spray_cost,
         management_fee,
         ROUND(total_cost_raw, 2) AS total_cost
  FROM components;
$function$;

COMMIT;

-- Verification examples after selecting lines:
-- SELECT calc.add_attachment_selection('TEST-001', 'JP_SINGLE', 'JP466060', NULL, 1);
-- SELECT * FROM calc.v_attachment_selection_cost WHERE quote_id = 'TEST-001';
-- SELECT calc.get_attachment_fee('TEST-001');
-- SELECT * FROM calc.calculate_total_cost_for_quote('TEST-001', 100, 4.20, 8.30, 1000, 300);
