/*
  V1.1: independent quick-quote experience library and dual quote API.

  Quick quotation is deliberately independent from the formula quotation:
  - it only reads calc.quick_quote_experience;
  - it never calls a part rule, material-weight formula or area formula;
  - matched base price = experience price × input perimeter / matched perimeter;
  - final quick cost = adjusted experience base price + selected attachment fee;
  - no match returns NULL plus quick_quote_missing, never 0.

  Run after the V1.0 database scripts (and after the formula total function).
*/
BEGIN;

CREATE TABLE IF NOT EXISTS calc.quick_quote_experience (
  quick_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code VARCHAR(40) NOT NULL,
  model_code VARCHAR(100),
  material_code VARCHAR(30) NOT NULL,
  reference_width_mm NUMERIC(12,3) NOT NULL CHECK (reference_width_mm > 0),
  reference_height_mm NUMERIC(12,3) NOT NULL CHECK (reference_height_mm > 0),
  reference_depth_mm NUMERIC(12,3) NOT NULL CHECK (reference_depth_mm > 0),
  min_width_mm NUMERIC(12,3),
  max_width_mm NUMERIC(12,3),
  min_height_mm NUMERIC(12,3),
  max_height_mm NUMERIC(12,3),
  min_depth_mm NUMERIC(12,3),
  max_depth_mm NUMERIC(12,3),
  quick_material_cost NUMERIC(14,6),
  quick_auxiliary_cost NUMERIC(14,6),
  quick_labor_cost NUMERIC(14,6),
  quick_attachment_fee NUMERIC(14,6),
  quick_spray_cost NUMERIC(14,6),
  quick_management_fee NUMERIC(14,6),
  quick_base_price NUMERIC(14,6),
  quick_total_cost NUMERIC(14,6) NOT NULL CHECK (quick_total_cost >= 0),
  effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
  effective_to DATE,
  source_file VARCHAR(255),
  source_sheet VARCHAR(128),
  source_row_no INTEGER,
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_quick_quote_material
    CHECK (material_code IN ('SECC','SUS304','SUS316')),
  CONSTRAINT ck_quick_quote_period
    CHECK (effective_to IS NULL OR effective_to > effective_from),
  CONSTRAINT ck_quick_quote_ranges
    CHECK ((min_width_mm IS NULL OR max_width_mm IS NULL OR max_width_mm >= min_width_mm)
       AND (min_height_mm IS NULL OR max_height_mm IS NULL OR max_height_mm >= min_height_mm)
       AND (min_depth_mm IS NULL OR max_depth_mm IS NULL OR max_depth_mm >= min_depth_mm))
);

ALTER TABLE calc.quick_quote_experience
  ADD COLUMN IF NOT EXISTS quick_base_price NUMERIC(14,6);

CREATE INDEX IF NOT EXISTS idx_quick_quote_lookup
  ON calc.quick_quote_experience
     (product_code, material_code, is_active, effective_from DESC);
CREATE INDEX IF NOT EXISTS idx_quick_quote_model
  ON calc.quick_quote_experience(product_code, model_code, material_code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_quick_quote_active_key
  ON calc.quick_quote_experience(
    product_code, COALESCE(model_code,''), material_code,
    reference_width_mm, reference_height_mm, reference_depth_mm,
    effective_from
  );

COMMENT ON TABLE calc.quick_quote_experience IS
  'Independent quick quotation base prices. The matcher reads quick_base_price only; formula tables and component formulas are not consulted.';
COMMENT ON COLUMN calc.quick_quote_experience.quick_total_cost IS
  'Legacy alias for the direct experience base price; the dual API adds selected attachment fee.';
COMMENT ON COLUMN calc.quick_quote_experience.quick_base_price IS
  'Direct experience base price from the quick-quote workbook; not derived from material weight, area, labor or parts.';

CREATE OR REPLACE FUNCTION calc.match_quick_quote(
  p_product_code VARCHAR,
  p_model_code VARCHAR DEFAULT NULL,
  p_material_code VARCHAR DEFAULT 'SECC',
  p_width_mm NUMERIC DEFAULT NULL,
  p_height_mm NUMERIC DEFAULT NULL,
  p_depth_mm NUMERIC DEFAULT NULL,
  p_as_of_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  quick_rule_id BIGINT,
  product_code VARCHAR,
  model_code VARCHAR,
  material_code VARCHAR,
  reference_width_mm NUMERIC,
  reference_height_mm NUMERIC,
  reference_depth_mm NUMERIC,
  quick_material_cost NUMERIC,
  quick_auxiliary_cost NUMERIC,
  quick_labor_cost NUMERIC,
  quick_attachment_fee NUMERIC,
  quick_spray_cost NUMERIC,
  quick_management_fee NUMERIC,
  quick_total_cost NUMERIC,
  match_method VARCHAR,
  dimension_distance NUMERIC
)
LANGUAGE SQL
STABLE
AS $function$
  WITH canonical AS (
    SELECT CASE p_product_code
      WHEN 'JC' THEN 'JC_EXP'
      WHEN 'JQ' THEN 'JQ_EXP'
      WHEN U&'\8D85\5BBDJP' THEN 'JP_WIDE_EXP'
      WHEN U&'\8D85\5BBDJS' THEN 'JS_WIDE_EXP'
      WHEN U&'\64CD\4F5C\53F0' THEN 'OP_TABLE_EXP'
      ELSE p_product_code END AS product_code
  ), candidates AS (
    SELECT q.*,
      CASE WHEN NULLIF(p_model_code,'') IS NOT NULL
                 AND NULLIF(q.model_code,'') = NULLIF(p_model_code,'')
           THEN 0 ELSE 1 END AS model_rank,
      CASE WHEN p_width_mm BETWEEN COALESCE(q.min_width_mm,q.reference_width_mm)
                              AND COALESCE(q.max_width_mm,q.reference_width_mm)
                 AND p_height_mm BETWEEN COALESCE(q.min_height_mm,q.reference_height_mm)
                              AND COALESCE(q.max_height_mm,q.reference_height_mm)
                 AND p_depth_mm BETWEEN COALESCE(q.min_depth_mm,q.reference_depth_mm)
                              AND COALESCE(q.max_depth_mm,q.reference_depth_mm)
           THEN 0 ELSE 1 END AS range_rank,
      sqrt(power(p_width_mm-q.reference_width_mm,2)
         + power(p_height_mm-q.reference_height_mm,2)
         + power(p_depth_mm-q.reference_depth_mm,2)) AS distance
    FROM calc.quick_quote_experience q
    CROSS JOIN canonical c
    WHERE q.product_code = c.product_code
      AND q.material_code = p_material_code
      AND q.is_active = TRUE
      AND q.effective_from <= p_as_of_date
      AND (q.effective_to IS NULL OR p_as_of_date < q.effective_to)
      AND p_width_mm IS NOT NULL AND p_height_mm IS NOT NULL AND p_depth_mm IS NOT NULL
  ), best AS (
    SELECT *
    FROM candidates
    ORDER BY model_rank, range_rank, distance, effective_from DESC, quick_rule_id DESC
    LIMIT 1
  )
  SELECT b.quick_rule_id,b.product_code,b.model_code,b.material_code,
         b.reference_width_mm,b.reference_height_mm,b.reference_depth_mm,
         b.quick_material_cost,b.quick_auxiliary_cost,b.quick_labor_cost,
         b.quick_attachment_fee,b.quick_spray_cost,b.quick_management_fee,
         ROUND(
           COALESCE(b.quick_base_price,b.quick_total_cost)
           * CASE
               WHEN 4 * (b.reference_width_mm + b.reference_height_mm + b.reference_depth_mm) > 0
               THEN 4 * (p_width_mm + p_height_mm + p_depth_mm)
                    / (4 * (b.reference_width_mm + b.reference_height_mm + b.reference_depth_mm))
               ELSE 1
             END,
           6
         ),
         CASE
           WHEN b.model_rank = 0 AND b.distance = 0 THEN 'exact_model_dimension'
           WHEN b.range_rank = 0 THEN 'dimension_range'
           ELSE 'nearest_dimension'
         END::VARCHAR,
         b.distance
  FROM best b;
$function$;

CREATE TABLE IF NOT EXISTS calc.dual_quote_result (
  quote_id VARCHAR(80) PRIMARY KEY,
  product_code VARCHAR(40) NOT NULL,
  model_code VARCHAR(100),
  material_code VARCHAR(30) NOT NULL,
  input_width_mm NUMERIC(12,3) NOT NULL,
  input_height_mm NUMERIC(12,3) NOT NULL,
  input_depth_mm NUMERIC(12,3) NOT NULL,
  quote_date DATE NOT NULL DEFAULT CURRENT_DATE,
  formula_material_cost NUMERIC(14,2),
  formula_auxiliary_cost NUMERIC(14,2),
  formula_labor_cost NUMERIC(14,2),
  formula_attachment_fee NUMERIC(14,2),
  formula_product_area_m2 NUMERIC(14,6),
  formula_spray_cost NUMERIC(14,2),
  formula_management_fee NUMERIC(14,2),
  formula_total_cost NUMERIC(14,2),
  quick_rule_id BIGINT,
  quick_match_method VARCHAR(40),
  quick_match_distance NUMERIC,
  quick_material_cost NUMERIC(14,6),
  quick_auxiliary_cost NUMERIC(14,6),
  quick_labor_cost NUMERIC(14,6),
  quick_attachment_fee NUMERIC(14,6),
  quick_spray_cost NUMERIC(14,6),
  quick_management_fee NUMERIC(14,6),
  quick_base_price NUMERIC(14,6),
  quick_total_cost NUMERIC(14,6),
  difference_cost NUMERIC(14,6),
  risk_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dual_quote_product_date
  ON calc.dual_quote_result(product_code, material_code, created_at DESC);

ALTER TABLE calc.dual_quote_result
  ADD COLUMN IF NOT EXISTS quick_base_price NUMERIC(14,6);

COMMENT ON COLUMN calc.dual_quote_result.quick_attachment_fee IS
  'Selected attachment fee added to the quick experience base price.';

CREATE OR REPLACE FUNCTION calc.calculate_dual_quote(
  p_quote_id VARCHAR,
  p_product_code VARCHAR,
  p_model_code VARCHAR,
  p_material_code VARCHAR,
  p_width_mm NUMERIC,
  p_height_mm NUMERIC,
  p_depth_mm NUMERIC,
  p_base_material_weight_kg NUMERIC DEFAULT NULL,
  p_product_area_m2 NUMERIC DEFAULT NULL,
  p_coating_type VARCHAR DEFAULT U&'\5E73\5149',
  p_variant_code VARCHAR DEFAULT NULL,
  p_quote_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  quote_id VARCHAR,
  product_code VARCHAR,
  model_code VARCHAR,
  material_code VARCHAR,
  formula_material_cost NUMERIC,
  formula_auxiliary_cost NUMERIC,
  formula_labor_cost NUMERIC,
  formula_attachment_fee NUMERIC,
  formula_product_area_m2 NUMERIC,
  formula_spray_cost NUMERIC,
  formula_management_fee NUMERIC,
  formula_total_cost NUMERIC,
  quick_rule_id BIGINT,
  quick_match_method VARCHAR,
  quick_match_distance NUMERIC,
  quick_material_cost NUMERIC,
  quick_auxiliary_cost NUMERIC,
  quick_labor_cost NUMERIC,
  quick_attachment_fee NUMERIC,
  quick_spray_cost NUMERIC,
  quick_management_fee NUMERIC,
  quick_total_cost NUMERIC,
  difference_cost NUMERIC,
  risk_flags JSONB
)
LANGUAGE plpgsql
VOLATILE
AS $function$
DECLARE
  v_formula RECORD;
  v_quick RECORD;
  v_risks JSONB := '[]'::jsonb;
  v_product_code VARCHAR;
  v_quick_attachment NUMERIC := 0;
  v_quick_base NUMERIC;
  v_quick_total NUMERIC;
  v_difference NUMERIC;
BEGIN
  IF p_quote_id IS NULL OR btrim(p_quote_id) = '' THEN
    RAISE EXCEPTION 'quote_id is required';
  END IF;
  IF p_material_code NOT IN ('SECC','SUS304','SUS316') THEN
    RAISE EXCEPTION 'unsupported material_code: %', p_material_code;
  END IF;
  IF p_width_mm IS NULL OR p_height_mm IS NULL OR p_depth_mm IS NULL
     OR p_width_mm <= 0 OR p_height_mm <= 0 OR p_depth_mm <= 0 THEN
    RAISE EXCEPTION 'width, height and depth must be positive';
  END IF;

  v_product_code := CASE p_product_code
    WHEN 'JC' THEN 'JC_EXP'
    WHEN 'JQ' THEN 'JQ_EXP'
    WHEN U&'\8D85\5BBDJP' THEN 'JP_WIDE_EXP'
    WHEN U&'\8D85\5BBDJS' THEN 'JS_WIDE_EXP'
    WHEN U&'\64CD\4F5C\53F0' THEN 'OP_TABLE_EXP'
    ELSE p_product_code END;

  /* Formula quotation remains the existing DB-owned calculation. */
  SELECT * INTO v_formula
  FROM calc.calculate_quote_total(
    p_quote_id, v_product_code, COALESCE(p_model_code,''), p_material_code,
    p_width_mm, p_height_mm, p_depth_mm, p_base_material_weight_kg,
    p_product_area_m2, p_coating_type, p_variant_code, p_quote_date);

  IF v_formula.material_cost IS NULL THEN
    v_risks := v_risks || jsonb_build_array(jsonb_build_object(
      'code','formula_material_cost_missing','severity','blocker'));
  END IF;

  /* Quick quotation reads experience values only. */
  SELECT * INTO v_quick
  FROM calc.match_quick_quote(
    v_product_code, p_model_code, p_material_code,
    p_width_mm, p_height_mm, p_depth_mm, p_quote_date);

  IF NOT FOUND THEN
    v_risks := v_risks || jsonb_build_array(jsonb_build_object(
      'code','quick_quote_missing','severity','blocker',
      'message',U&'\5F85\8865\5145\7ECF\9A8C\503C'));
    v_quick_total := NULL;
  ELSE
    /* match_quick_quote returns the direct quick base in quick_total_cost.
       It intentionally does not expose formula-derived components. */
    v_quick_base := v_quick.quick_total_cost;
    v_quick_attachment := COALESCE(calc.get_attachment_fee(p_quote_id, v_product_code), 0);
    v_quick_total := v_quick_base + v_quick_attachment;
  END IF;

  IF v_formula.total_cost IS NOT NULL AND v_quick_total IS NOT NULL THEN
    v_difference := ROUND(v_quick_total - v_formula.total_cost, 2);
  END IF;

  /* A quote_id is the logical version key. Replace the previous snapshot
     before writing the new one; this also makes repeated smoke tests safe. */
  DELETE FROM calc.dual_quote_result
   WHERE calc.dual_quote_result.quote_id = $1;

  INSERT INTO calc.dual_quote_result(
    quote_id,product_code,model_code,material_code,
    input_width_mm,input_height_mm,input_depth_mm,quote_date,
    formula_material_cost,formula_auxiliary_cost,formula_labor_cost,
    formula_attachment_fee,formula_product_area_m2,formula_spray_cost,
    formula_management_fee,formula_total_cost,
    quick_rule_id,quick_match_method,quick_match_distance,
    quick_material_cost,quick_auxiliary_cost,quick_labor_cost,
    quick_attachment_fee,quick_spray_cost,quick_management_fee,quick_base_price,
    quick_total_cost,difference_cost,risk_flags,updated_at)
  VALUES(
    p_quote_id,v_product_code,p_model_code,p_material_code,
    p_width_mm,p_height_mm,p_depth_mm,p_quote_date,
    v_formula.material_cost,v_formula.auxiliary_cost,v_formula.labor_cost,
    v_formula.attachment_fee,v_formula.product_area_m2,v_formula.spray_cost,
    v_formula.management_fee,v_formula.total_cost,
    v_quick.quick_rule_id,v_quick.match_method,v_quick.dimension_distance,
    v_quick.quick_material_cost,v_quick.quick_auxiliary_cost,v_quick.quick_labor_cost,
    v_quick_attachment,v_quick.quick_spray_cost,v_quick.quick_management_fee,v_quick_base,
    v_quick_total,v_difference,v_risks,now());

  RETURN QUERY SELECT
    p_quote_id,v_product_code,p_model_code,p_material_code,
    v_formula.material_cost,v_formula.auxiliary_cost,v_formula.labor_cost,
    v_formula.attachment_fee,v_formula.product_area_m2,v_formula.spray_cost,
    v_formula.management_fee,v_formula.total_cost,
    v_quick.quick_rule_id,v_quick.match_method,v_quick.dimension_distance,
    v_quick.quick_material_cost,v_quick.quick_auxiliary_cost,v_quick.quick_labor_cost,
    v_quick_attachment,v_quick.quick_spray_cost,v_quick.quick_management_fee,
    v_quick_total,v_difference,v_risks;
END;
$function$;

COMMENT ON FUNCTION calc.calculate_dual_quote IS
  'Returns formula quotation and independent quick experience quotation in one call. Quick total is experience base price plus selected attachment fee; missing quick values remain NULL and are flagged.';

COMMIT;

/* Verification before importing quick prices: quick_total_cost must be NULL. */
-- SELECT * FROM calc.calculate_dual_quote(
--   'TEST-DUAL-JS-001','JS_SINGLE','', 'SECC',
--   1000,1800,600,49.068134,6.047482,U&'\6A58\7EB9','SINGLE',CURRENT_DATE);
