// Local test fixture only. Does not connect to any database or contain real quote rows.
import fs from 'node:fs/promises';
import path from 'node:path';
const [source,output,evidence]=process.argv.slice(2);
if(!source||!output||!evidence) throw new Error('usage: node build_attachment_schema_fixture.mjs report.txt fixture.sql evidence.json');
const report=JSON.parse(await fs.readFile(source,'utf8'));
const names=['attachment_price','attachment_classification','attachment_selection'];
const quote=name=>'"'+name.replaceAll('"','""')+'"';
const allowedTypes=new Set(['bigint','integer','smallint','numeric','character varying','text','date','boolean','timestamp with time zone']);
const lines=['-- LOCAL TEST ONLY. Structure transcribed from user-provided online preflight, 2026-09-11.',
  '-- All inserted rows are synthetic. Never execute this fixture on the online database.','CREATE SCHEMA calc;'];
for(const name of names){
  const columns=report.columns.filter(c=>c.table_name===name);
  if(!columns.length) throw new Error('Missing table '+name);
  lines.push(`CREATE TABLE calc.${quote(name)} (\n${columns.map(c=>{
    if(!allowedTypes.has(c.data_type)) throw new Error('Unsupported type '+c.data_type);
    let type=c.data_type;
    if(type==='character varying') type+=`(${c.character_maximum_length})`;
    if(type==='numeric'&&c.numeric_precision!==null) type+=`(${c.numeric_precision},${c.numeric_scale})`;
    // Report establishes identity, but not ALWAYS/BY DEFAULT; tests use defaults only.
    return `  ${quote(c.column_name)} ${type}`+(c.is_identity==='YES'?' GENERATED BY DEFAULT AS IDENTITY':c.column_default!==null?` DEFAULT ${c.column_default}`:'')+(c.is_nullable==='NO'?' NOT NULL':'');
  }).join(',\n')}\n);`);
}
for(const c of report.constraints.filter(c=>['p','u','c','f'].includes(c.contype)).sort((a,b)=>(a.contype==='f')-(b.contype==='f'))){
  if(!names.some(n=>c.source_table===`calc.${n}`)) throw new Error('External FK needs independent fixture review');
  lines.push(`ALTER TABLE ${c.source_table} ADD CONSTRAINT ${quote(c.conname)} ${c.definition};`);
}
for(const i of report.indexes){
  if(!report.constraints.some(c=>c.conname===i.indexname&&['p','u'].includes(c.contype))) lines.push(i.indexdef+';');
}
if(report.triggers.length||report.policies.length) throw new Error('Triggers/RLS need explicit test fixture handling');
for(const v of report.views) lines.push(`CREATE VIEW calc.${quote(v.viewname)} AS ${v.definition}`);
// Only functions whose complete dependencies are the three copied tables/views.
// Full original definitions, including other quote functions, remain in evidence.json.
for(const f of report.functions.filter(f=>/^calc\.(get_attachment_fee|get_attachment_price|add_attachment_selection)\(/.test(f.signature))) lines.push(f.definition+';');
lines.push(`INSERT INTO calc.attachment_price(attachment_category,item_name,price,source_file,source_sheet,source_row_no)
VALUES('旧分类','历史附件',12.34,'fixture','fixture',1);
INSERT INTO calc.attachment_classification(attachment_price_id,category_level1) VALUES(1,'旧分类');
INSERT INTO calc.attachment_selection(quote_id,product_code,attachment_price_id,item_name,unit_price)
VALUES('HISTORY','JP',1,'历史附件',12.34);`);
await fs.mkdir(path.dirname(output),{recursive:true});
await fs.writeFile(output,lines.join('\n\n')+'\n');
await fs.mkdir(path.dirname(evidence),{recursive:true});
await fs.writeFile(evidence,JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({columns:report.columns.length,constraints:report.constraints.length,indexes:report.indexes.length,views:report.views.length,triggers:report.triggers.length,policies:report.policies.length}));
