-- LOCAL TEST ONLY. Structure transcribed from user-provided online preflight, 2026-09-11.

-- All inserted rows are synthetic. Never execute this fixture on the online database.

CREATE SCHEMA calc;

CREATE TABLE calc."attachment_price" (
  "attachment_price_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "attachment_category" character varying(40) NOT NULL,
  "item_name" character varying(160) NOT NULL,
  "model_code" character varying(100),
  "variant" character varying(80),
  "material_code" character varying(30),
  "width_mm" integer,
  "height_mm" integer,
  "depth_mm" integer,
  "unit" character varying(20),
  "price" numeric(14,4),
  "price_text" character varying(120),
  "price_source" character varying(40) DEFAULT '表格价'::character varying NOT NULL,
  "notes" text,
  "source_file" character varying(255) NOT NULL,
  "source_sheet" character varying(80) NOT NULL,
  "source_row_no" integer NOT NULL,
  "effective_from" date DEFAULT CURRENT_DATE NOT NULL,
  "effective_to" date,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "cost_method" character varying(20) DEFAULT 'experience'::character varying NOT NULL
);

CREATE TABLE calc."attachment_classification" (
  "attachment_price_id" bigint NOT NULL,
  "category_level1" character varying(80) NOT NULL,
  "category_level2" character varying(160),
  "category_level3" character varying(200),
  "classification_source" character varying(120) DEFAULT 'attachment-catalog-20260824'::character varying NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE calc."attachment_selection" (
  "attachment_selection_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "quote_id" character varying(80) NOT NULL,
  "product_code" character varying(40),
  "model_code" character varying(100),
  "attachment_price_id" bigint,
  "item_name" character varying(160),
  "variant" character varying(80),
  "price_source" character varying(40),
  "quantity" numeric(14,4) DEFAULT 1 NOT NULL,
  "unit_price" numeric(14,4),
  "price_text" character varying(120),
  "cost_method" character varying(20) DEFAULT 'experience'::character varying NOT NULL,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "price_sign" smallint DEFAULT 1 NOT NULL
);

ALTER TABLE calc.attachment_classification ADD CONSTRAINT "attachment_classification_category_level1_check" CHECK ((btrim((category_level1)::text) <> ''::text));

ALTER TABLE calc.attachment_classification ADD CONSTRAINT "attachment_classification_category_level1_check1" CHECK (((category_level1)::text <> '26'::text));

ALTER TABLE calc.attachment_classification ADD CONSTRAINT "attachment_classification_category_level2_check" CHECK (((category_level2 IS NULL) OR ((category_level2)::text <> '26'::text)));

ALTER TABLE calc.attachment_classification ADD CONSTRAINT "attachment_classification_category_level3_check" CHECK (((category_level3 IS NULL) OR ((category_level3)::text <> '26'::text)));

ALTER TABLE calc.attachment_classification ADD CONSTRAINT "attachment_classification_pkey" PRIMARY KEY (attachment_price_id);

ALTER TABLE calc.attachment_price ADD CONSTRAINT "attachment_price_pkey" PRIMARY KEY (attachment_price_id);

ALTER TABLE calc.attachment_price ADD CONSTRAINT "ck_attachment_price_nonnegative" CHECK (((price IS NULL) OR (price >= (0)::numeric)));

ALTER TABLE calc.attachment_price ADD CONSTRAINT "ck_attachment_price_period" CHECK (((effective_to IS NULL) OR (effective_to > effective_from)));

ALTER TABLE calc.attachment_price ADD CONSTRAINT "uq_attachment_price_source" UNIQUE (source_file, source_sheet, source_row_no, price_source);

ALTER TABLE calc.attachment_selection ADD CONSTRAINT "attachment_selection_pkey" PRIMARY KEY (attachment_selection_id);

ALTER TABLE calc.attachment_selection ADD CONSTRAINT "attachment_selection_price_sign_check" CHECK ((price_sign = ANY (ARRAY['-1'::integer, 1])));

ALTER TABLE calc.attachment_selection ADD CONSTRAINT "attachment_selection_quantity_check" CHECK ((quantity >= (0)::numeric));

ALTER TABLE calc.attachment_selection ADD CONSTRAINT "attachment_selection_unit_price_check" CHECK (((unit_price IS NULL) OR (unit_price >= (0)::numeric)));

ALTER TABLE calc.attachment_classification ADD CONSTRAINT "attachment_classification_attachment_price_id_fkey" FOREIGN KEY (attachment_price_id) REFERENCES calc.attachment_price(attachment_price_id) ON DELETE CASCADE;

ALTER TABLE calc.attachment_selection ADD CONSTRAINT "attachment_selection_attachment_price_id_fkey" FOREIGN KEY (attachment_price_id) REFERENCES calc.attachment_price(attachment_price_id);

CREATE INDEX idx_attachment_classification_levels ON calc.attachment_classification USING btree (category_level1, category_level2, category_level3);

CREATE INDEX idx_attachment_price_dims ON calc.attachment_price USING btree (attachment_category, width_mm, height_mm, depth_mm, is_active);

CREATE INDEX idx_attachment_price_item ON calc.attachment_price USING btree (item_name, variant, price_source, is_active);

CREATE INDEX idx_attachment_price_model ON calc.attachment_price USING btree (model_code, attachment_category, is_active);

CREATE INDEX idx_attachment_selection_model ON calc.attachment_selection USING btree (model_code, item_name);

CREATE INDEX idx_attachment_selection_quote ON calc.attachment_selection USING btree (quote_id, product_code);

CREATE VIEW calc."v_attachment_selection_cost" AS  SELECT s.attachment_selection_id,
 s.quote_id,
 s.product_code,
 s.model_code,
 s.attachment_price_id,
 s.item_name,
 s.variant,
 s.price_source,
 s.quantity,
 s.unit_price,
 s.price_text,
 s.cost_method,
 COALESCE(s.unit_price, p.price) AS effective_unit_price,
 CASE
 WHEN (COALESCE(s.unit_price, p.price) IS NULL) THEN NULL::numeric
 ELSE round(((s.quantity * COALESCE(s.unit_price, p.price)) * (s.price_sign)::numeric), 2)
 END AS line_cost,
 s.notes,
 s.created_at,
 s.updated_at,
 s.price_sign
 FROM (calc.attachment_selection s
 LEFT JOIN calc.attachment_price p ON ((p.attachment_price_id = s.attachment_price_id)));

CREATE VIEW calc."v_attachment_price" AS  SELECT attachment_price_id,
 attachment_category,
 item_name,
 model_code,
 variant,
 material_code,
 width_mm,
 height_mm,
 depth_mm,
 unit,
 price,
 price_text,
 price_source,
 notes,
 source_file,
 source_sheet,
 source_row_no,
 effective_from,
 effective_to,
 is_active,
 created_at,
 updated_at,
 cost_method
 FROM calc.attachment_price
 WHERE (is_active = true);

CREATE VIEW calc."v_attachment_price_classified" AS  SELECT p.attachment_price_id,
 p.attachment_category,
 p.item_name,
 p.model_code,
 p.variant,
 p.material_code,
 p.width_mm,
 p.height_mm,
 p.depth_mm,
 p.unit,
 p.price,
 p.price_text,
 p.price_source,
 p.notes,
 p.source_file,
 p.source_sheet,
 p.source_row_no,
 p.effective_from,
 p.effective_to,
 p.is_active,
 p.created_at,
 p.updated_at,
 p.cost_method,
 c.category_level1,
 c.category_level2,
 c.category_level3,
 c.classification_source,
 c.updated_at AS classification_updated_at
 FROM (calc.attachment_price p
 LEFT JOIN calc.attachment_classification c ON ((c.attachment_price_id = p.attachment_price_id)));

CREATE OR REPLACE FUNCTION calc.add_attachment_selection(p_quote_id character varying, p_product_code character varying DEFAULT NULL::character varying, p_model_code character varying DEFAULT NULL::character varying, p_item_name character varying DEFAULT NULL::character varying, p_quantity numeric DEFAULT 1, p_width_mm integer DEFAULT NULL::integer, p_height_mm integer DEFAULT NULL::integer, p_depth_mm integer DEFAULT NULL::integer, p_variant character varying DEFAULT NULL::character varying, p_price_source character varying DEFAULT NULL::character varying, p_unit_price_override numeric DEFAULT NULL::numeric, p_notes text DEFAULT NULL::text)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
 v_price calc.attachment_price%ROWTYPE;
 v_selection_id BIGINT;
BEGIN
 IF p_quote_id IS NULL OR btrim(p_quote_id) = '' THEN
 RAISE EXCEPTION 'quote_id is required';
 END IF;
 IF p_model_code IS NULL AND p_item_name IS NULL THEN
 RAISE EXCEPTION 'model_code or item_name is required';
 END IF;
 IF p_quantity IS NULL OR p_quantity < 0 THEN
 RAISE EXCEPTION 'quantity must be non-negative';
 END IF;

 SELECT ap.*
 INTO v_price
 FROM calc.attachment_price ap
 WHERE ap.is_active = TRUE
 AND (p_model_code IS NULL OR ap.model_code = p_model_code OR ap.model_code IS NULL OR ap.model_code = '所有型号')
 AND (p_item_name IS NULL OR ap.item_name = p_item_name)
 AND (p_width_mm IS NULL OR ap.width_mm = p_width_mm)
 AND (p_height_mm IS NULL OR ap.height_mm = p_height_mm)
 AND (p_depth_mm IS NULL OR ap.depth_mm = p_depth_mm)
 AND (p_variant IS NULL OR ap.variant = p_variant OR ap.variant IS NULL)
 AND (p_price_source IS NULL OR ap.price_source = p_price_source)
 ORDER BY
 CASE WHEN ap.model_code = p_model_code THEN 0 ELSE 1 END,
 CASE WHEN ap.item_name = p_item_name THEN 0 ELSE 1 END,
 ap.attachment_price_id DESC
 LIMIT 1;

 IF NOT FOUND THEN
 RAISE EXCEPTION 'attachment price not found: model=%, item=%, variant=%, source=%',
 p_model_code, p_item_name, p_variant, p_price_source;
 END IF;

 INSERT INTO calc.attachment_selection (
 quote_id, product_code, model_code, attachment_price_id,
 item_name, variant, price_source, quantity, unit_price,
 price_text, cost_method, notes
 )
 VALUES (
 p_quote_id, p_product_code, v_price.model_code, v_price.attachment_price_id,
 v_price.item_name, v_price.variant, v_price.price_source, p_quantity,
 COALESCE(p_unit_price_override, v_price.price), v_price.price_text,
 'experience', p_notes
 )
 RETURNING attachment_selection_id INTO v_selection_id;

 RETURN v_selection_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION calc.get_attachment_fee(p_quote_id character varying, p_product_code character varying DEFAULT NULL::character varying)
 RETURNS numeric
 LANGUAGE sql
 STABLE
AS $function$
 SELECT COALESCE(ROUND(SUM(v.line_cost), 2), 0)
 FROM calc.v_attachment_selection_cost v
 WHERE v.quote_id = p_quote_id
 AND (p_product_code IS NULL OR v.product_code = p_product_code);
$function$
;

CREATE OR REPLACE FUNCTION calc.get_attachment_price(p_model_code character varying DEFAULT NULL::character varying, p_item_name character varying DEFAULT NULL::character varying, p_width_mm integer DEFAULT NULL::integer, p_height_mm integer DEFAULT NULL::integer, p_depth_mm integer DEFAULT NULL::integer, p_variant character varying DEFAULT NULL::character varying, p_price_source character varying DEFAULT NULL::character varying)
 RETURNS numeric
 LANGUAGE sql
 STABLE
AS $function$
 SELECT ap.price
 FROM calc.attachment_price ap
 WHERE ap.is_active = TRUE
 AND ap.price IS NOT NULL
 AND (p_model_code IS NULL OR ap.model_code = p_model_code OR ap.model_code IS NULL OR ap.model_code = '所有型号')
 AND (p_item_name IS NULL OR ap.item_name = p_item_name)
 AND (p_width_mm IS NULL OR ap.width_mm = p_width_mm)
 AND (p_height_mm IS NULL OR ap.height_mm = p_height_mm)
 AND (p_depth_mm IS NULL OR ap.depth_mm = p_depth_mm)
 AND (p_variant IS NULL OR ap.variant = p_variant OR ap.variant IS NULL)
 AND (p_price_source IS NULL OR ap.price_source = p_price_source)
 ORDER BY
 CASE WHEN ap.model_code = p_model_code THEN 0 ELSE 1 END,
 CASE WHEN ap.item_name = p_item_name THEN 0 ELSE 1 END,
 ap.attachment_price_id DESC
 LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION calc.add_attachment_selection(p_quote_id character varying, p_product_code character varying DEFAULT NULL::character varying, p_model_code character varying DEFAULT NULL::character varying, p_item_name character varying DEFAULT NULL::character varying, p_quantity numeric DEFAULT 1, p_width_mm integer DEFAULT NULL::integer, p_height_mm integer DEFAULT NULL::integer, p_depth_mm integer DEFAULT NULL::integer, p_variant character varying DEFAULT NULL::character varying, p_price_source character varying DEFAULT NULL::character varying, p_unit_price_override numeric DEFAULT NULL::numeric, p_notes text DEFAULT NULL::text, p_price_sign smallint DEFAULT 1)
 RETURNS bigint
 LANGUAGE plpgsql
AS $function$
DECLARE
 v_price calc.attachment_price%ROWTYPE;
 v_selection_id BIGINT;
 v_attachment_text TEXT;
BEGIN
 IF p_quote_id IS NULL OR btrim(p_quote_id) = '' THEN
 RAISE EXCEPTION 'quote_id is required';
 END IF;
 IF p_model_code IS NULL AND p_item_name IS NULL THEN
 RAISE EXCEPTION 'model_code or item_name is required';
 END IF;
 IF p_quantity IS NULL OR p_quantity < 0 THEN
 RAISE EXCEPTION 'quantity must be non-negative';
 END IF;
 IF p_price_sign NOT IN (-1, 1) THEN
 RAISE EXCEPTION 'price_sign must be 1 or -1';
 END IF;

 v_attachment_text := COALESCE(p_item_name, '') || ' ' || COALESCE(p_model_code, '');
 IF p_price_sign = -1
 AND (position('安装板' IN v_attachment_text) = 0 OR position('安装板单发' IN v_attachment_text) > 0) THEN
 RAISE EXCEPTION 'negative price_sign is allowed only for an installation board';
 END IF;

 SELECT ap.*
 INTO v_price
 FROM calc.attachment_price ap
 WHERE ap.is_active = TRUE
 AND (p_model_code IS NULL OR ap.model_code = p_model_code OR ap.model_code IS NULL OR ap.model_code = '所有型号')
 AND (p_item_name IS NULL OR ap.item_name = p_item_name)
 AND (p_width_mm IS NULL OR ap.width_mm = p_width_mm)
 AND (p_height_mm IS NULL OR ap.height_mm = p_height_mm)
 AND (p_depth_mm IS NULL OR ap.depth_mm = p_depth_mm)
 AND (p_variant IS NULL OR ap.variant = p_variant OR ap.variant IS NULL)
 AND (p_price_source IS NULL OR ap.price_source = p_price_source)
 ORDER BY
 CASE WHEN ap.model_code = p_model_code THEN 0 ELSE 1 END,
 CASE WHEN ap.item_name = p_item_name THEN 0 ELSE 1 END,
 ap.attachment_price_id DESC
 LIMIT 1;

 IF NOT FOUND THEN
 RAISE EXCEPTION 'attachment price not found: model=%, item=%, variant=%, source=%',
 p_model_code, p_item_name, p_variant, p_price_source;
 END IF;

 INSERT INTO calc.attachment_selection (
 quote_id, product_code, model_code, attachment_price_id,
 item_name, variant, price_source, quantity, unit_price,
 price_text, cost_method, notes, price_sign
 )
 VALUES (
 p_quote_id, p_product_code, v_price.model_code, v_price.attachment_price_id,
 v_price.item_name, v_price.variant, v_price.price_source, p_quantity,
 COALESCE(p_unit_price_override, v_price.price), v_price.price_text,
 'experience', p_notes, p_price_sign
 )
 RETURNING attachment_selection_id INTO v_selection_id;

 RETURN v_selection_id;
END;
$function$
;

INSERT INTO calc.attachment_price(attachment_category,item_name,price,source_file,source_sheet,source_row_no)
VALUES('旧分类','历史附件',12.34,'fixture','fixture',1);
INSERT INTO calc.attachment_classification(attachment_price_id,category_level1) VALUES(1,'旧分类');
INSERT INTO calc.attachment_selection(quote_id,product_code,attachment_price_id,item_name,unit_price)
VALUES('HISTORY','JP',1,'历史附件',12.34);
